### ISSUE TITLE
Main menu text garbled Tang25k

### ISSUE THREAD

**Issue by rvkasper** [nand2mario/snestang#19]
Love the project - I think possibly the latest zip for release 0.7 has an outdated firmware causing the issue I am seeing - just a guess? I flashed snestang_primer25k_ds2.fs and the apr5 firmware that comes with it but the menu is unresponsive with garbled text

**Comment by radiance28** [comment]
Can you provide any screenshot or tell me if this software worked for you before?  On my Primer25K the latest firmware works fine, nothing is corrupted

**Comment by rvkasper** [comment]
> Can you provide any screenshot or tell me if this software worked for you before? On my Primer25K the latest firmware works fine, nothing is corrupted

Yup ill take a pic now

**Comment by rvkasper** [comment]
> Can you provide any screenshot or tell me if this software worked for you before? On my Primer25K the latest firmware works fine, nothing is corrupted

![PXL_20240518_215748245](https://github.com/nand2mario/snestang/assets/10135006/b717f248-85a5-4cce-bf35-d58f8b873dea)

**Comment by nand2mario** [comment]
Cannot reproduce. Close fo rnow.

**Comment by rvkasper** [comment]
> Cannot reproduce. Close fo rnow.

fine in 0.8 - thanks! man the sound is PERFECT now. Was the v0.7 release only for those with snes controllers? i flashed it for the sound fix even though im using dualshocks - maybe thats why...
keep up the great work
