### ISSUE TITLE
Usage with Tang Mega 138k

### ISSUE THREAD

**Issue by suitable-name** [nand2mario/snestang#2]
Hi,
i saw the project file for the tang mega 138k and thought I'd just try it. I connected the PMODS the same way as on the Tang Primer 25k, but it didn't work out of the box (no . Since I didn't find any further resources in this git, despite the project file, I thought I'd just ask if this is still work in progress or if there is anything that should be considered. Thanks!

**Comment by nand2mario** [comment]
0.2 should work. It is configured to use the on-board SD and HDMI output. So only the DS2 pmod is needed (the left-most pmod connector). HDMI output is the "DVI output" port.

0.3 has a new memory controller. So m138k is not working currently.

**Comment by nand2mario** [comment]
I've uploaded a build for Tang Mega 138K, along with instructions.

https://github.com/nand2mario/snestang/releases/tag/v0.4_m138k

**Comment by suitable-name** [comment]
Thanks for the update, I'm closing this issue for now and going to check it out this weekend! :)
