### ISSUE TITLE
SD Card error on tang primer 25k w/ TF PMOD v1

### ISSUE THREAD

**Issue by ovodomina** [nand2mario/snestang#21]
Hello. I have an SD card error. The red LED flashes when turned on, but does not access the card (a message appears quickly, error 99). The same card works normally on Tang Primer 20k. I'm using PMOD SDCard V2.

**Comment by siffland** [comment]
I have the same issue, I cannot get any card to be read in my primer 25k PMOD V2 module, but the card words with snestang in my 20k.  Same error.  I have dried Samsung, Sandisk, and PNY cards all have the same issue.

**Comment by ovodomina** [comment]
I tested with version 0.6 and PMOD 1.0.  It worked.  I will try to compile a current version with PMOD V1.0

**Comment by nand2mario** [comment]
Right, the code is switched to TF PMOD v2 since 0.6.1. Using the v0.6 pin locations for sd_* pins in src/primer25k/snestang.cst should allow use of TF PMOD v1.
