### ISSUE TITLE
sdcard access is broken on v0.8

### ISSUE THREAD

**Issue by wiebel** [nand2mario/snestang#25]
I was able to run nestang-v0.11 fine and switched the core to snetang-v0.8 alright, but the snestang core was not able to access the sdcard, neither the .bin nor the .fs worked. On first access the sd seemed fine for a directory listing, but on any read/write operation the sd became inaccessible. v0.7 works flawlessly.
I'm using a genuine SanDisk Ultra 32G, bought a few weeks ago.

**Comment by radiance28** [comment]
I confirm.  Once, when switching from one core to another, my memory card deteriorated and all the contents disappeared, and the PC prompted me to format it.

**Comment by nand2mario** [comment]
> I was able to run nestang-v0.11 fine and switched the core to snetang-v0.8 alright, but the snestang core was not able to access the sdcard, neither the .bin nor the .fs worked. On first access the sd seemed fine for a directory listing, but on any read/write operation the sd became inaccessible. v0.7 works flawlessly.
> 
> I'm using a genuine SanDisk Ultra 32G, bought a few weeks ago.

Are you on the nano 20k or primer 25k?

**Comment by wiebel** [comment]
Sorry for the late answer. I have the primer 25k
