### ISSUE TITLE
Tang Mega 138K -> SD card not working

### ISSUE THREAD

**Issue by suitable-name** [nand2mario/snestang#4]
Hey, 
thanks for the new release! I just tried it with my Tang Mega 138k. Basically the emulator is starting, also the controller is working, but it can't open the files on SD card. I used the slot as shown on the picture and tried the same card I've been using before on the Tang 25k. I tried to format the card with exFAT, FAT16 and FAT32. For a split second I see the message, the directory can't be opened and nothing further happens. I'm using a SanDisk Ultra Card with 32gb.  
Can you help me with that?
I also tried to build the bitstream myself, but the vram.v file is missing in the mega138k folder (available in the git repo itself of course, just missing in the zip archive).

Update: I also tried v0.3 and v0.4 on the Tang 25k. In both cases no data could be read from the sd card. After going back to v0.2 it was working again. I made sure to set the offset for the firmware correct, but for some reason on the newer versions the data from the card can't be read.

Thanks!

**Comment by siffland** [comment]
I can verify, I just upgraded from v0.2 to v0.4 and the SDcard does not work for me, on the bottom of the screen when i choose select rom i see 

`Error opening director 99`

Flash on the bottom of the screen briefly.  I tried Samsung and Sandisk cards formatted in exfat and fat32 and two different sdcard pmods.

**Comment by nand2mario** [comment]
Error 99 is SD initialization error. The new SD code needs some more work. Could you provide model number or picture of your card? I'll try to replicate.

**Comment by smist09** [comment]
Which exact SD Card do you support? I have a Digilent pmod, but the pins seem to be different than the cst file. Similarly I received a sipeed tf and one of the pins seems different than the cst file. So far no luck getting either to work. Running putty I can see where in the initialization code they fail, will try to debug.

**Comment by suitable-name** [comment]
This is the card I'm using:
![signal-2024-02-20-182929_002](https://github.com/nand2mario/snestang/assets/130936649/ff1e5139-bb21-4ae5-9f2e-e9ce521a0886)
![signal-2024-02-20-182929_003](https://github.com/nand2mario/snestang/assets/130936649/27b04e05-7748-4acf-8b01-7c22c694b234)

**Comment by nand2mario** [comment]
Oh, for Tang Mega 138k you don't need the pmod. Just insert the sd card into the TF slot on the back of the board.

**Comment by smist09** [comment]
Sorry, I tacked this on to this issue, I'm using a Tang Primer 25k. Didn't check, just assumed the 138k was similar.

**Comment by nand2mario** [comment]
> This is the card I'm using: 

I've ordered this card and will test it.

**Comment by suitable-name** [comment]
> > This is the card I'm using:
> 
> I've ordered this card and will test it.

Thats great, thanks for your support!

**Comment by nand2mario** [comment]
Can you check if the new 0.5 release solved the SD card problem? The 9 cards I have on hand all work now.

**Comment by smist09** [comment]
Yes that works. Thank you. That is using the Sipeed card pmod.

**Comment by suitable-name** [comment]
I'm a little bit late for the party and didn't test it yet, but also big thanks from my side!

**Comment by suitable-name** [comment]
I was finally able to test it and it works all perfect. Even games that didn't work before (like Mario Kart) are working as expected now, thanks!
